const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94776114551"
const SESSION_ID = "PRABATH-MD~qdsXRAwR#I9_ZMgPlmDwiKLX7vg3qYB6znjd-aqZT9Q8YED6vbds"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
